//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanCaPhe_CNPM
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONGTHUC
    {
        public string MaMon { get; set; }
        public string MaNL { get; set; }
        public string HamLuong { get; set; }
    
        public virtual NGUYENLIEU NGUYENLIEU { get; set; }
        public virtual THUCDON THUCDON { get; set; }
    }
}
