//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanCaPhe_CNPM
{
    using System;
    using System.Collections.Generic;
    
    public partial class TINHLUONG
    {
        public string MaNV { get; set; }
        public string HoTen { get; set; }
        public Nullable<int> Thang { get; set; }
        public Nullable<int> Nam { get; set; }
        public Nullable<int> TongSoCa { get; set; }
        public Nullable<int> LuongCoBan { get; set; }
        public Nullable<int> Luong { get; set; }
    }
}
