//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanCaPhe_CNPM
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHAMCONG
    {
        public string MaNV { get; set; }
        public System.DateTime NgayLam { get; set; }
        public string MaCa { get; set; }
    
        public virtual CA CA { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
