//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanCaPhe_CNPM
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETHDON
    {
        public string MaHoaDon { get; set; }
        public string MaMon { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<int> DonGia { get; set; }
        public Nullable<int> ThanhTien { get; set; }
    
        public virtual HDON HDON { get; set; }
        public virtual THUCDON THUCDON { get; set; }
    }
}
