//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanCaPhe_CNPM
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON
    {
        public string MaHoaDon { get; set; }
        public System.DateTime NgayTao { get; set; }
        public string MaBan { get; set; }
        public string MaMon { get; set; }
        public string TenMon { get; set; }
        public string DVT { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<int> DonGia { get; set; }
        public Nullable<int> ThanhTien { get; set; }
        public string TenKH { get; set; }
        public string MaThue { get; set; }
        public string MaKH { get; set; }
        public string VAT { get; set; }
        public string HoTen { get; set; }
    }
}
